# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: force
    routing_loader: false
    body_converter:
      enabled: true
      validate: true
    view:
        view_response_listener: force
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json' ], fallback_format: json, prefer_extension: true }
            - { path: '^/*', priorities: [ 'json' ], fallback_format: json, prefer_extension: true }
#    zone:
#      - { path: ^/api/* }
