# Deployed by {{ gitlab_ci_pipeline_url }}
version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    restart: on-failure
    volumes:
      - ./:/var/www/
    ports:
      - '8788:80'
    expose:
      - '8888'
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    restart: on-failure
    environment:
      XDEBUG_CONFIG: client_host=10.254.254.254 idekey=user-loader-docker
      XDEBUG_MODE: "debug"
    volumes:
      - ./:/var/www/
    expose:
      - '9000'

  app-db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: verysecret
      POSTGRES_USER: user
      POSTGRES_DB: dev
    volumes:
      - type: volume
        source: user_loader_data
        target: /var/lib/postgresql
    ports:
      - '5433:5432'
volumes:
  user_loader_data: